### PR TITLE
Make library better

### PR DESCRIPTION
**Pull request by bendrucker**
:trollface:

### CODE REVIEW

**Comment by ajoslin** [comment]
With this implementation, when used in the browser, we have to have `window.Promise` available. That's quite an assumption.

The implementation in https://github.com/notjrbauer/promise.waterfall/pull/2 doesn't make this assumption.

**Comment by notjrbauer** [comment]
@bendrucker While I recognize your efforts of gumption, my goal was to be as obscure as possible. Needs more curry; although I will welcome a PR for updating the readme!

@ajoslin Thank you as well, but this was strictly intended for engineers. I plan on revising this to use `async wait` once it's properly optimized by v8.

Thanks and like always, cheers!

**Comment by bendrucker** [comment]
Needs more DTOs

**Comment by bendrucker** [comment]
Forreal though, want me to cherry pick the docs cleanup to master?

**Comment by notjrbauer** [comment]
Yes you're more than welcomed to!

Thanks and like always, cheers!

**Comment by bendrucker** [comment]
@bendrucker's commits merged: 1 :trophy: 
@ajoslin's commits merged: 0 :hankey: 

cheers mate

**Pull request closed without merging**
